<section><h2>발송할 템플릿</h2><form method="get" action="<?= $this->e($base) ?>/modules/alimtalk/send"><input type="hidden" name="environment" value="<?= $this->e($environment) ?>"><label for="template_id">템플릿 선택</label><select id="template_id" name="template_id" required><option value="">선택해 주세요</option><?php foreach ($templates as $item): if (!$item['enabled']) continue; ?><option value="<?= $this->e($item['id']) ?>"<?= ($selected['id'] ?? '') === $item['id'] ? ' selected' : '' ?>><?= $this->e($item['name']) ?></option><?php endforeach ?></select><button>입력 화면 열기</button></form></section>
<?php if ($selected !== null): ?><section><h2>수신번호와 변수</h2><form method="post" action="<?= $this->e($base) ?>/modules/alimtalk/send">
<input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="environment" value="<?= $this->e($environment) ?>"><input type="hidden" name="template_id" value="<?= $this->e($selected['id']) ?>"><input type="hidden" name="revision" value="<?= $this->e($selected['revision']) ?>">
<label for="phone">수신 휴대폰 번호</label><input id="phone" name="phone" inputmode="tel" required value="<?= $this->e(is_string($values['phone'] ?? null) ? $values['phone'] : '') ?>">
<?php foreach ($selected['variables'] as $i => $variable): ?><label for="variable-<?= $i ?>"><?= $this->e($variable) ?></label><input id="variable-<?= $i ?>" name="variables[<?= $this->e($variable) ?>]" required maxlength="1000" value="<?= $this->e(is_string($values['variables'][$variable] ?? null) ? $values['variables'][$variable] : '') ?>"><?php endforeach ?><button name="action" value="preview">내용 미리보기</button></form></section><?php endif ?>
<?php if ($preview !== null): ?><section><h2>최종 발송 내용</h2><p><strong><?= $environment === 'live' ? '운영' : '검수' ?></strong> · 수신번호 <?= $this->e($values['phone']) ?></p><pre><?= $this->e($preview['message']) ?></pre>
<?php foreach ($preview['buttons'] as $button): ?><p><strong><?= $this->e($button['name']) ?></strong><br><?= $this->e($button['url_mobile']) ?><?php if (isset($button['url_pc'])): ?><br><?= $this->e($button['url_pc']) ?><?php endif ?></p><?php endforeach ?>
<p>버튼을 누르면 비즈뿌리오로 실제 발송을 요청합니다. 검수 환경의 수신·과금 조건은 계정 계약을 따릅니다.</p>
<?php if (!$account_status['enabled']): ?><p class="errors">현재 발송이 정지되어 있습니다. 플러그인 설정에서 발송을 허용한 뒤 진행해 주세요.</p><?php endif ?>
<form method="post" action="<?= $this->e($base) ?>/modules/alimtalk/send"><input type="hidden" name="csrf_token" value="<?= $this->e($csrf_token) ?>"><input type="hidden" name="environment" value="<?= $this->e($environment) ?>"><input type="hidden" name="confirmation" value="<?= $this->e($confirmation) ?>"><button name="action" value="send"<?= !$account_status['enabled'] ? ' disabled' : '' ?>>확인한 번호로 알림톡 발송</button></form></section><?php endif ?>
