<?php if ($order['claims'] !== []): ?><section class="panel<?= !empty($admin_screen) ? ' card card-body extension-panel' : '' ?>"><h2 class="card-title">취소·반품·교환 진행</h2><?php $kinds = ['return' => '반품', 'exchange' => '교환', 'cancel' => '주문 취소']; foreach ($order['claims'] as $claim): ?>
<article class="claim"><h3 class="form-section-title"><?= $this->e($kinds[$claim['kind']]) ?> <?= (int) $claim['quantity'] > 0 ? (int) $claim['quantity'] . '개' : '' ?> · <span class="badge badge-soft"><?= $this->e($status_labels[$claim['status']]) ?></span></h3><p><?= $this->e($claim['reason']) ?></p><?php if ($claim['note']): ?><p class="muted"><?= $this->e($claim['note']) ?></p><?php endif ?><?php if ($claim['tracking']): ?><p>교환 배송: <?= $this->e($claim['carrier'] . ' ' . $claim['tracking']) ?></p><?php endif ?><small><?= $this->e($time($claim['created_at'])) ?></small>
<?php foreach ($order['items'] as $claimItem): if ($claimItem['id'] !== $claim['item_id']) continue; ?>
<p><strong>신청 상품</strong> <?= $this->e($claimItem['name']) ?> · <?= $this->e($claimItem['options'] ?: '기본 상품') ?></p>
<?php endforeach ?>
<?php if ($claim['kind'] === 'exchange'): foreach ($replacement_options[$claim['item_id']] ?? [] as $replacement): if ($replacement['id'] !== $claim['replacement_id']) continue; ?>
<p><strong>교환받을 옵션</strong> <?= $this->e(implode(' / ', array_filter([$replacement['option1'], $replacement['option2']])) ?: '기본 상품') ?></p>
<?php endforeach; endif ?>
<?php if ($claim['kind'] !== 'cancel' && in_array($claim['status'], ['received', 'refund_pending', 'completed'], true)): ?><p class="muted">회수품 검수: <?= (int) $claim['restock'] ? '재판매 가능' : '재판매 불가' ?></p><?php endif ?>
<?php if ($manage && in_array($claim['status'], ['requested', 'approved', 'received'], true)): ?>
<form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="claim_id" value="<?= $this->e($claim['id']) ?>"><input type="hidden" name="action" value="claim-action">
<?php if ($claim['status'] === 'requested'): ?><div class="row"><button class="btn btn-primary" name="claim_action" value="approve">신청 승인</button></div><?php endif ?>
<?php if (in_array($claim['status'], ['requested', 'approved'], true)): ?><label class="extension-label">거절 사유 / 검수 메모<input class="input input-bordered input-block" name="note" maxlength="1000"></label><div class="row"><button name="claim_action" value="reject" class="secondary btn">신청 거절</button><?php if ($claim['status'] === 'approved' && $claim['kind'] !== 'cancel'): ?><label class="extension-label"><input class="checkbox checkbox-primary checkbox-sm" type="checkbox" name="restock" value="1">회수품 재판매 가능</label><button class="btn btn-primary" name="claim_action" value="receive">상품 회수·검수 완료</button><?php endif ?></div><?php endif ?>
<?php if ($claim['status'] === 'received' && $claim['kind'] === 'exchange'): ?><div class="row"><label class="extension-label">교환 택배사<input class="input input-bordered input-block" name="carrier" maxlength="80" required></label><label class="extension-label">교환 운송장<input class="input input-bordered input-block" name="tracking" maxlength="80" required></label><button class="btn btn-primary" name="claim_action" value="exchange">교환품 발송 완료</button></div><p class="muted">교환 옵션 재고를 차감하고 재판매 가능한 회수품만 재고로 돌려놓습니다.</p><?php endif ?></form>
<?php if (($claim['kind'] === 'return' && $claim['status'] === 'received') || ($claim['kind'] === 'cancel' && in_array($claim['status'], ['requested', 'approved'], true))): ?>
<form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="claim_id" value="<?= $this->e($claim['id']) ?>"><input type="hidden" name="request_key" value="<?= $this->e(substr(hash('sha256', $request_key . $claim['id']), 0, 32)) ?>"><input type="hidden" name="reason" value="<?= $this->e($kinds[$claim['kind']] . ' 처리') ?>">
<?php $amount = (int) $order['total'] - (int) $order['refunded']; if ($claim['kind'] === 'return') { foreach ($order['items'] as $i) if ($i['id'] === $claim['item_id']) $amount = (int) $i['price'] * (int) $claim['quantity']; } ?>
<p><strong>상품 환불 <?= number_format($amount) ?>원</strong></p><?php if ($claim['kind'] === 'return' && (int) $order['shipping'] > (int) $order['shipping_refunded']): ?><label class="extension-label"><input class="checkbox checkbox-primary checkbox-sm" type="checkbox" name="include_shipping" value="1">최초 배송비 <?= number_format((int) $order['shipping'] - (int) $order['shipping_refunded']) ?>원도 환불</label><?php endif ?>
<?php if ($claim['kind'] === 'return'): ?><label class="extension-label">정책에 따라 고객과 확인한 반품 비용 공제 (원)<input class="input input-bordered input-block" name="deduction" type="number" value="0" min="0" max="1000000" required></label><p class="muted">환불액 = 반품 상품 금액 + 선택한 최초 배송비 − 반품 비용. 반품 비용은 고객과 확인한 금액만 입력하세요.</p><?php endif ?>
<button name="action" value="refund" class="danger btn btn-error">금액 확인 후 환불 요청</button></form><?php endif ?>
<?php if ($claim['status'] === 'received'): ?>
<details><summary>검수 후 처리 변경</summary>
<p class="muted">교환품이 품절이면 고객과 확인하고 반품·환불로 전환할 수 있습니다. 검수 후 신청을 거절할 때에는 회수품을 고객에게 돌려보내는 방법을 사유에 기록해 주세요. 신청 거절은 환불이나 재고를 변경하지 않습니다.</p>
<form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="claim_id" value="<?= $this->e($claim['id']) ?>"><input type="hidden" name="action" value="claim-action"><label class="extension-label">고객과 확인한 처리 사유<textarea class="textarea textarea-bordered textarea-block" name="note" maxlength="1000" required></textarea></label><div class="row"><?php if ($claim['kind'] === 'exchange'): ?><button name="claim_action" value="convert-return" class="secondary btn">반품·환불로 전환</button><?php endif ?><button name="claim_action" value="reject" class="secondary btn">검수 후 신청 거절</button></div></form>
</details><?php endif ?>
<?php endif ?></article><?php endforeach ?></section><?php endif ?>
