<?php if ($order !== null): $manage = $page === 'manage-order'; $actionUrl = $url . '/' . $page; ?>
<div class="toolbar"><div><p class="eyebrow">Order detail</p><h1><?= $this->e($status_labels[$order['status']] ?? $order['status']) ?></h1><p class="order-id"><?= $this->e($order['id']) ?></p><p class="muted"><?= $this->e($time($order['created_at'])) ?> · <?= $this->e($providers[$order['provider']]) ?><?php if ($order['environment'] === 'test'): ?> · 테스트 주문<?php endif ?></p></div><a href="<?= $this->e($url) ?>/<?= $manage ? 'admin' : 'orders' ?>">← 주문 목록</a></div>
<?php if ($order['needs_review']): ?><div class="alert">결제 내역 확인이 필요합니다. 운영자가 결제사의 주문번호·금액·환불 내역을 확인한 뒤 처리합니다.</div><?php endif ?>
<section class="panel"><div class="row"><form method="post" action="<?= $this->e($actionUrl) ?>"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><button name="action" value="sync" class="secondary">결제·환불 상태 조회</button></form>
<?php if ($order['status'] === 'pending'): ?>
<?php if (!$manage && (int) $order['expires_at'] >= $now): ?><form method="post" action="<?= $this->e($actionUrl) ?>"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><button name="action" value="pay"><?= number_format((int) $order['total']) ?>원 결제 준비</button></form><?php endif ?>
<form method="post" action="<?= $this->e($actionUrl) ?>"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><button name="action" value="cancel-pending" class="secondary">미결제 주문 취소</button></form>
<?php endif ?></div><?php if ($order['status'] === 'pending'): ?><p class="muted">결제 기한 <?= $this->e($time($order['expires_at'])) ?>. 결제를 마쳤다면 상태 조회를 눌러 확인해 주세요.</p><?php endif ?>
<?php if ($payment !== null): ?><div class="notice"><p>결제 금액을 확인했습니다. 카드 결제창을 열어 결제를 마쳐 주세요.</p>
<form id="shop-payment-form" method="post" action="<?= $this->e($payment['action'] ?? '') ?>" accept-charset="<?= $this->e($payment['charset'] ?? 'UTF-8') ?>">
<?php foreach ($payment['fields'] as $field => $value): ?><input type="hidden" name="<?= $this->e($field) ?>" value="<?= $this->e($value) ?>"><?php endforeach ?>
<button type="<?= in_array($payment['kind'], ['inicis', 'toss'], true) ? 'button' : 'submit' ?>" id="shop-pay-button"><?= $payment['kind'] === 'toss' ? '카드·간편결제창 열기' : '카드 결제창 열기' ?></button></form><p id="shop-payment-message" role="status"></p></div>
<?php if ($payment['kind'] === 'inicis'): ?>
<script src="<?= $this->e($payment['script']) ?>"></script>
<script>(()=>{'use strict';const button=document.getElementById('shop-pay-button'),message=document.getElementById('shop-payment-message');button.addEventListener('click',()=>{if(!window.INIStdPay){message.textContent='결제창 연결을 확인해 주세요.';return;}window.INIStdPay.pay('shop-payment-form');});})();</script>
<?php elseif ($payment['kind'] === 'toss'): ?>
<script src="<?= $this->e($payment['script']) ?>"></script>
<script>(()=>{'use strict';const options=<?= json_encode(['clientKey' => $payment['client_key'], 'customerKey' => $payment['customer_key'], 'request' => $payment['request']], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT | JSON_THROW_ON_ERROR) ?>;
const button=document.getElementById('shop-pay-button'),message=document.getElementById('shop-payment-message');
button.addEventListener('click',async()=>{if(button.disabled)return;button.disabled=true;message.textContent='결제창을 여는 중입니다.';
try{if(!window.TossPayments)throw new Error();await window.TossPayments(options.clientKey).payment({customerKey:options.customerKey}).requestPayment(options.request);}
catch(error){message.textContent=error&&error.code==='USER_CANCEL'?'결제를 취소했습니다. 다시 결제할 수 있습니다.':'결제창 연결을 확인한 뒤 다시 시도해 주세요.';button.disabled=false;}});})();</script>
<?php endif ?>
<?php endif ?></section>
<div class="cols"><section class="panel table-wrap"><h2>주문 상품</h2><table><thead><tr><th>상품 / 옵션</th><th class="num">단가</th><th class="num">수량</th><th class="num">반품 / 교환</th></tr></thead><tbody><?php foreach ($order['items'] as $item): ?><tr><td><?= $this->e($item['name']) ?><br><small><?= $this->e($item['options']) ?></small></td><td class="num"><?= number_format((int) $item['price']) ?>원</td><td class="num"><?= (int) $item['quantity'] ?>개</td><td class="num"><?= (int) $item['returned'] ?> / <?= (int) $item['exchanged'] ?></td></tr><?php endforeach ?></tbody></table></section>
<aside class="panel"><h2>결제 금액</h2><div class="summary-line"><span>상품 금액</span><strong><?= number_format((int) $order['total'] - (int) $order['shipping']) ?>원</strong></div><div class="summary-line"><span>배송비</span><strong><?= number_format((int) $order['shipping']) ?>원</strong></div><div class="summary-line"><span>주문 합계</span><strong><?= number_format((int) $order['total']) ?>원</strong></div><div class="summary-line"><span>확정 환불</span><strong><?= number_format((int) $order['refunded']) ?>원</strong></div><div class="summary-line total"><span>남은 금액</span><strong><?= number_format((int) $order['total'] - (int) $order['refunded']) ?>원</strong></div></aside></div>
<div class="cols"><section class="panel"><h2>배송 정보</h2><p><strong><?= $this->e($order['customer_data']['name']) ?></strong> · <?= $this->e($order['customer_data']['phone']) ?></p><p><?= $this->e($order['customer_data']['email']) ?></p><p>[<?= $this->e($order['customer_data']['postcode']) ?>] <?= $this->e($order['customer_data']['address'] . ' ' . $order['customer_data']['address_detail']) ?></p><p class="pre muted"><?= $this->e($order['customer_data']['memo']) ?></p><?php if ($order['tracking']): ?><p><strong><?= $this->e($order['carrier']) ?></strong> · 운송장 <?= $this->e($order['tracking']) ?></p><?php endif ?></section><section class="panel"><h2>주문 시 동의한 정책</h2><details><summary>배송·반품 정책 보기</summary><div class="policy pre"><?= $this->e($order['customer_data']['policy']) ?></div></details></section></div>
<?php if ($manage): ?>
<section class="panel stack"><h2>배송 처리</h2><form method="post" action="<?= $this->e($actionUrl) ?>" class="row"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><?php if ($order['status'] === 'paid'): ?><button name="action" value="pack" class="secondary">상품 준비 시작</button><?php endif ?><?php if (in_array($order['status'], ['paid', 'packing'], true)): ?><label>택배사<input name="carrier" maxlength="80"></label><label>운송장 번호<input name="tracking" maxlength="80"></label><button name="action" value="ship">배송 시작</button><?php elseif ($order['status'] === 'shipped'): ?><button name="action" value="deliver">배송 완료 처리</button><?php else: ?><p class="muted">현재 상태에서 새 출고 작업은 없습니다.</p><?php endif ?></form></section>
<?php if (in_array($order['status'], ['paid', 'packing'], true)): ?><section class="panel"><h2>배송 전 전액 환불</h2><p>확정 취소 후 판매 가능 재고를 돌려놓습니다. 중복 환불을 막기 위해 기존 환불이 있으면 먼저 결과를 조회합니다.</p><form method="post" action="<?= $this->e($actionUrl) ?>" class="row"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="request_key" value="<?= $this->e($request_key) ?>"><label>환불 사유<input name="reason" maxlength="150" required></label><button name="action" value="refund" class="danger"><?= number_format((int) $order['total'] - (int) $order['refunded']) ?>원 전액 환불</button></form></section><?php endif ?>
<?php endif ?>
<?php if (in_array($order['status'], ['paid', 'packing'], true) && !$manage): ?><section class="panel"><h2>주문 취소 신청</h2><form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="request_key" value="<?= $this->e($request_key) ?>"><input type="hidden" name="action" value="claim"><input type="hidden" name="kind" value="cancel"><label>취소 사유<textarea name="reason" maxlength="1000" required></textarea></label><button class="secondary">배송 전 취소 신청</button></form></section><?php endif ?>
<?php if (in_array($order['status'], ['shipped', 'delivered'], true)): ?>
<section class="panel"><h2>반품·교환 신청</h2><p class="muted">교환은 같은 상품의 동일 가격 옵션으로 가능합니다. 차액이 있으면 반품 후 다시 주문해 주세요.</p><?php foreach ($order['items'] as $item): $available = (int) $item['quantity'] - (int) $item['returned'] - (int) $item['exchanged']; if ($available < 1) continue; ?>
<details class="claim"><summary><?= $this->e($item['name'] . ' · ' . $item['options']) ?> 신청</summary><form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="item_id" value="<?= $this->e($item['id']) ?>"><input type="hidden" name="action" value="claim"><input type="hidden" name="request_key" value="<?= $this->e(substr(hash('sha256', $request_key . $item['id']), 0, 32)) ?>"><div class="form-grid"><label>신청 종류<select name="kind"><option value="return">반품·환불</option><option value="exchange">교환</option></select></label><label>수량<input name="quantity" type="number" min="1" max="<?= $available ?>" value="1" required></label><label class="full">교환받을 옵션 (반품 신청 시 무시)<select name="replacement_id"><option value="">선택</option><?php foreach ($replacement_options[$item['id']] ?? [] as $variant): if (!(int) $variant['active'] || (int) $variant['price'] !== (int) $item['price']) continue; ?><option value="<?= $this->e($variant['id']) ?>"><?= $this->e(implode(' / ', array_filter([$variant['option1'], $variant['option2']])) ?: '기본 상품') ?> · 재고 <?= (int) $variant['stock'] ?></option><?php endforeach ?></select></label><label class="full">신청 사유<textarea name="reason" maxlength="1000" required></textarea></label></div><button class="secondary">신청 접수</button></form></details><?php endforeach ?></section>
<?php endif ?>
<?php $this->insert('_claims', ['manage' => $manage, 'actionUrl' => $actionUrl]) ?>
<?php if ($order['refunds'] !== []): ?><section class="panel table-wrap"><h2>환불 내역</h2><table><thead><tr><th>요청 일시</th><th>상태</th><th class="num">환불 금액</th><th>확인</th></tr></thead><tbody><?php foreach ($order['refunds'] as $refund): ?><tr><td><?= $this->e($time($refund['created_at'])) ?></td><td><?= $this->e($refund['status'] === 'pending' ? '환불 확인 중' : ($status_labels[$refund['status']] ?? $refund['status'])) ?></td><td class="num"><?= number_format((int) $refund['amount']) ?>원<?php if ((int) $refund['deduction'] > 0): ?><br><small>반품 비용 <?= number_format((int) $refund['deduction']) ?>원 공제</small><?php endif ?></td><td><?php if ($manage && $refund['status'] === 'pending'): ?><form method="post" action="<?= $this->e($actionUrl) ?>"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="refund_id" value="<?= $this->e($refund['id']) ?>"><button class="secondary" name="action" value="retry-refund">환불 상태 확인</button></form><details><summary>결제사 수동 취소 연결</summary><form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="refund_id" value="<?= $this->e($refund['id']) ?>"><label>확정 취소 ID<input name="reference" required></label><label>결제사 확인 메모<input name="note" required></label><button name="action" value="attach-refund">기존 환불에 연결</button></form></details><?php else: ?><small><?= $this->e($refund['provider_ref'] ?? '결제사 결과 확인 중') ?></small><?php endif ?></td></tr><?php endforeach ?></tbody></table><p class="muted">응답이 끊긴 환불은 자동으로 다시 전송하지 않습니다. 결제사 내역을 확인한 뒤 확정 취소를 연결하거나 미처리를 확인해 주세요.</p></section><?php endif ?>
<?php if ($manage && $order['needs_review']): ?><section class="panel"><h2>결제·재고 대조 완료</h2><p>결제사 내역과 재고를 대조하고 보류 환불 결과를 확인한 뒤 확인 표시를 해제합니다. 금액이나 상점 코드가 다르면 해제할 수 없습니다.</p><form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><label>확인 근거와 재고 처리 메모<textarea name="note" required maxlength="1000"></textarea></label><button name="action" value="review" class="secondary">대조 완료 기록</button></form></section><?php endif ?>
<?php if ($manage): foreach ($order['refunds'] as $refund): if ($refund['status'] !== 'pending' || $now - (int) $refund['created_at'] <= 7200) continue; ?><section class="panel"><details><summary>장기 보류 환불 <?= number_format((int) $refund['amount']) ?>원 · 결제사 미처리 확인</summary><p>결제사에서 이 환불이 처리되지 않았음을 직접 확인했을 때만 사용합니다. 성공한 수동 취소가 있으면 외부 취소 연결을 사용하세요.</p><form method="post" action="<?= $this->e($actionUrl) ?>" class="stack"><?php $this->insert('_csrf') ?><input type="hidden" name="id" value="<?= $this->e($order['id']) ?>"><input type="hidden" name="refund_id" value="<?= $this->e($refund['id']) ?>"><label>결제사 확인 일시·담당자·근거<textarea name="note" maxlength="1000" required></textarea></label><button name="action" value="close-refund" class="secondary">미처리 확인 후 보류 종료</button></form></details></section><?php endforeach; endif ?>
<?php if ($manage): ?><section class="panel"><h2>확정 결제 원장</h2><div class="table-wrap"><table><thead><tr><th>일시</th><th>구분</th><th class="num">금액</th><th>거래·취소 ID</th></tr></thead><tbody><?php foreach ($money as $entry): ?><tr><td><?= $this->e($time($entry['occurred_at'])) ?></td><td><?= $entry['kind'] === 'payment' ? '결제' : '환불' ?></td><td class="num"><?= number_format((int) $entry['amount']) ?>원</td><td class="order-id"><?= $this->e($entry['reference']) ?></td></tr><?php endforeach ?></tbody></table></div><details><summary>주문 처리 이력</summary><?php foreach ($order['events'] as $event): ?><p><small><?= $this->e($time($event['created_at'])) ?></small> <?= $this->e($event['kind']) ?> · <?= $this->e($event['note']) ?> <small>(<?= $this->e($event['actor']) ?>)</small></p><?php endforeach ?></details></section><?php endif ?>
<?php endif ?>
